In [39]:
import pandas as pd

In [40]:
clinvar = pd.read_excel("clinvar_result_final_tabulated.xlsx")

# Load CFTR2 (multiple sheets)
cftr2_sheets = pd.read_excel("CFTR2_30January2026.xlsx", sheet_name=None)

sheet1 = cftr2_sheets[list(cftr2_sheets.keys())[0]]
sheet2 = cftr2_sheets[list(cftr2_sheets.keys())[1]]

print(clinvar.shape, sheet1.shape, sheet2.shape)

(1387, 25) (2099, 9) (2173, 13)

In [41]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.replace("\n", " ")
        .str.replace(r"\s+", " ", regex=True)
    )
    return df

sheet1 = clean_columns(sheet1)
sheet2 = clean_columns(sheet2)
clinvar = clean_columns(clinvar)

In [42]:
cftr2 = pd.merge(
    sheet1,
    sheet2,
    on="Variant cDNA name",
    how="inner"   # ensures only matched rows
)

In [43]:
print(cftr2.columns)

Index(['Variant legacy name_x', 'Variant protein name', 'Variant cDNA name',
       'Variant alternative names (other names that may have been used in the past)',
       '# alleles reported in CFTR2',
       'Allele frequency in CFTR2* (of 211106 identified alleles)',
       'Variant final determination 25 September 2024 (previous version)',
       'Variant final determination 30 January 2026 (current version)',
       'Change from previous?', 'Variant legacy name_y', 'Notes',
       'hgvs_genomic_grch37', 'hgvs_genomic_grch38', 'grch37_chr',
       'grch37_pos', 'grch37_ref', 'grch37_alt', 'grch38_chr', 'grch38_pos',
       'grch38_ref', 'grch38_alt'],
      dtype='object')

In [44]:
cftr2.head()

,Variant legacy name_x,Variant protein name,Variant cDNA name,Variant alternative names (other names that may have been used in the past),# alleles reported in CFTR2,Allele frequency in CFTR2* (of 211106 identified alleles),Variant final determination 25 September 2024 (previous version),Variant final determination 30 January 2026 (current version),Change from previous?,Variant legacy name_y,...,hgvs_genomic_grch37,hgvs_genomic_grch38,grch37_chr,grch37_pos,grch37_ref,grch37_alt,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,F508del,p.Phe508del,c.1521_1523del,"c.1521_1523del, 1653delCTT",137363,0.650683,CF-causing,CF-causing,No,F508del,...,NC_000007.13:g.117199646_117199648del,NC_000007.14:g.117559592_117559594del,7.0,117199644.0,ATCT,A,7.0,117559590.0,ATCT,A
1,G542X,p.Gly542X,c.1624G>T,1756G>T,5752,0.027247,CF-causing,CF-causing,No,G542X,...,NC_000007.13:g.117227832G>T,NC_000007.14:g.117587778G>T,7.0,117227832.0,G,T,7.0,117587778.0,G,T
2,G551D,p.Gly551Asp,c.1652G>A,1784G>A,3831,0.018147,CF-causing,CF-causing,No,G551D,...,NC_000007.13:g.117227860G>A,NC_000007.14:g.117587806G>A,7.0,117227860.0,G,A,7.0,117587806.0,G,A
3,N1303K,p.Asn1303Lys,c.3909C>G,4041C>G,3551,0.016821,CF-causing,CF-causing,No,N1303K,...,NC_000007.13:g.117292931C>G,NC_000007.14:g.117652877C>G,7.0,117292931.0,C,G,7.0,117652877.0,C,G
4,R117H,p.Arg117His,c.350G>A,482G>A,2262,0.010715,Varying clinical consequence,Varying clinical consequence,No,R117H,...,NC_000007.13:g.117171029G>A,NC_000007.14:g.117530975G>A,7.0,117171029.0,G,A,7.0,117530975.0,G,A

In [45]:
clinvar = clinvar[[
    "Name",
    "GRCh38Chromosome",
    "GRCh38Location",
    "Canonical SPDI",
    "dbSNP ID",
    "Variant type",
    "Molecular consequence",
    "Germline classification",
]]

cftr2 = cftr2[[
    "Variant cDNA name",
    "Variant final determination 30 January 2026 (current version)",
    "Variant cDNA name",
    "hgvs_genomic_grch38",
    "grch38_chr",
    "grch38_pos",
    "grch38_ref",
    "grch38_alt"
]]

In [46]:
clinvar.head(15)

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Molecular consequence,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,NaN,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,NaN,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,NaN,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,NaN,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,NaN,Benign
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,NaN,Benign
6,NM_000492.3(CFTR):c.1210-12T[9],7,117548628 - 117548629,NC_000007.14:117548628:TTTTTTT:TTTTTTTTT,rs1805177,Duplication,intron variant,Benign/Likely benign
7,NM_000492.3(CFTR):c.1521_1523del (p.Phe508del),7,117559591 - 117559593,NC_000007.14:117559590:TCTT:T,rs113993960,Deletion,inframe_deletion,Pathogenic
8,NM_000492.3(CFTR):c.2175dup (p.Glu726Argfs),7,117592340 - 117592341,NC_000007.14:117592340:AA:AAA,rs746418935,Duplication,frameshift variant,Pathogenic
9,NM_000492.3(CFTR):c.2909_2924dupGTGGGATTCTTAATAG,7,117606669 - 117606670,NC_000007.14:117606669:ATAGGTGGGATTCTTAATAG:AT...,NaN,Duplication,NaN,Pathogenic/Likely pathogenic
10,NM_000492.3(CFTR):c.2909delG,7,117606673,NC_000007.14:117606672:GG:G,rs397508458,Deletion,NaN,Pathogenic
11,NM_000492.3(CFTR):c.3468+2dup,7,117614714 - 117614715,NC_000007.14:117614714:T:TT,rs1554392800,Duplication,splice donor variant,Pathogenic
12,NM_000492.3(CFTR):c.3718-2477C>T,7,117639961,NC_000007.14:117639960:C:T,rs75039782,single nucleotide variant,intron variant,Pathogenic
13,NM_000492.3(CFTR):c.3965_3969dup,7,117664686 - 117664687,NC_000007.14:117664686:GGTTGGG:GGTTGGGTTGGG,rs1209386423,Duplication,NaN,Pathogenic
14,NM_000492.3(CFTR):c.[1075C>A;1079C>A],7|7,117540305,NC_000007.14:117540304:C:A|NC_000007.14:117540...,rs76879328|rs75053309,Haplotype,missense variant,Pathogenic

In [47]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),Variant cDNA name,hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,c.1521_1523del,NC_000007.14:g.117559592_117559594del,7.0,117559590.0,ATCT,A
1,c.1624G>T,CF-causing,c.1624G>T,NC_000007.14:g.117587778G>T,7.0,117587778.0,G,T
2,c.1652G>A,CF-causing,c.1652G>A,NC_000007.14:g.117587806G>A,7.0,117587806.0,G,A
3,c.3909C>G,CF-causing,c.3909C>G,NC_000007.14:g.117652877C>G,7.0,117652877.0,C,G
4,c.350G>A,Varying clinical consequence,c.350G>A,NC_000007.14:g.117530975G>A,7.0,117530975.0,G,A

In [48]:
clinvar.drop(columns=["Molecular consequence"], axis = 1, inplace = True)

In [49]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign

In [50]:
cftr2.dtypes

Variant cDNA name                                                 object
Variant final determination 30 January 2026 (current version)     object
Variant cDNA name                                                 object
hgvs_genomic_grch38                                               object
grch38_chr                                                       float64
grch38_pos                                                       float64
grch38_ref                                                        object
grch38_alt                                                        object
dtype: object

In [51]:
clinvar.dtypes

Name                       object
GRCh38Chromosome           object
GRCh38Location             object
Canonical SPDI             object
dbSNP ID                   object
Variant type               object
Germline classification    object
dtype: object

In [52]:
cftr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2026 entries, 0 to 2025
Data columns (total 8 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Variant cDNA name                                              2026 non-null   object
 1   Variant final determination 30 January 2026 (current version)  2026 non-null   object
 2   Variant cDNA name                                              2026 non-null   object
 3   hgvs_genomic_grch38                                            1823 non-null   object
 4   grch38_chr                                                     1823 non-null   float64
 5   grch38_pos                                                     1823 non-null   float64
 6   grch38_ref                                                     1823 non-null   object
 7   grch38_alt                                                     1823 non-null   object
dtypes: float64(2), object(6)
memory usage: 126.8+ KB

In [53]:
cftr2.dropna(inplace = True)

In [54]:
cftr2["grch38_chr"] = cftr2["grch38_chr"].astype(int)
cftr2['grch38_pos'] = cftr2['grch38_pos'].astype(int)

In [55]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),Variant cDNA name,hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,c.1521_1523del,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A
1,c.1624G>T,CF-causing,c.1624G>T,NC_000007.14:g.117587778G>T,7,117587778,G,T
2,c.1652G>A,CF-causing,c.1652G>A,NC_000007.14:g.117587806G>A,7,117587806,G,A
3,c.3909C>G,CF-causing,c.3909C>G,NC_000007.14:g.117652877C>G,7,117652877,C,G
4,c.350G>A,Varying clinical consequence,c.350G>A,NC_000007.14:g.117530975G>A,7,117530975,G,A

In [56]:
cftr2 = cftr2.iloc[:, [0, 1, 3, 4, 5, 6, 7]]

In [57]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7,117587778,G,T
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7,117587806,G,A
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7,117652877,C,G
4,c.350G>A,Varying clinical consequence,NC_000007.14:g.117530975G>A,7,117530975,G,A

In [58]:
cftr2["Variant final determination 30 January 2026 (current version)"].value_counts()

Variant final determination 30 January 2026 (current version)
CF-causing                      1091
No interpretation available      617
Varying clinical consequence      78
Non CF-causing                    37
Name: count, dtype: int64

In [59]:
cftr2.rename(columns = {"Variant final determination 30 January 2026 (current version)" : "variant determination"}, inplace = True)

In [60]:
cftr2.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7,117587778,G,T
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7,117587806,G,A
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7,117652877,C,G
4,c.350G>A,Varying clinical consequence,NC_000007.14:g.117530975G>A,7,117530975,G,A

In [61]:
cftr2 = cftr2[cftr2["variant determination"].isin(["CF-causing", "Non CF-causing"])]

In [62]:
cftr2["cause"] = cftr2["variant determination"].map({"CF-causing" : 1, "Non CF-causing" : 0})

In [63]:
cftr2["cause"].value_counts()

cause
1    1091
0      37
Name: count, dtype: int64

In [64]:
cftr2.rename(columns = {"grch38_chr" : "chr", 
    "grch38_pos": "pos",
    "grch38_ref": "ref",
    "grch38_alt": "alt"
}, inplace = True)

In [65]:
cftr2.to_csv("cftr2_cleaned.csv", index = False)

In [66]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign

In [67]:
clinvar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1387 entries, 0 to 1386
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     1387 non-null   object
 1   GRCh38Chromosome         1387 non-null   object
 2   GRCh38Location           1387 non-null   object
 3   Canonical SPDI           1387 non-null   object
 4   dbSNP ID                 1262 non-null   object
 5   Variant type             1387 non-null   object
 6   Germline classification  1387 non-null   object
dtypes: object(7)
memory usage: 76.0+ KB

In [68]:
clinvar["GRCh38Chromosome"] = 7

In [69]:
def loc_map(location):
    start_loc = location.split(" - ")[0]
    return int(start_loc)

clinvar["pos"] = clinvar["GRCh38Location"].apply(loc_map)

In [70]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic,117603679
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129

In [71]:
clinvar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1387 entries, 0 to 1386
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     1387 non-null   object
 1   GRCh38Chromosome         1387 non-null   int64
 2   GRCh38Location           1387 non-null   object
 3   Canonical SPDI           1387 non-null   object
 4   dbSNP ID                 1262 non-null   object
 5   Variant type             1387 non-null   object
 6   Germline classification  1387 non-null   object
 7   pos                      1387 non-null   int64
dtypes: int64(2), object(6)
memory usage: 86.8+ KB

In [72]:
def spdi_ref(spdi):
    try:
        chrom, pos, ref, alt = spdi.split(":")
        return ref
    except:
        return None
    
def spdi_alt(spdi):
    try:
        chrom, pos, ref, alt = spdi.split(":")
        return alt
    except:
        return None
    
clinvar["ref"] = clinvar["Canonical SPDI"].apply(spdi_ref)
clinvar["alt"] = clinvar["Canonical SPDI"].apply(spdi_alt)
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos,ref,alt
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226,TTTTTTTTT,TTTTTTTT
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898,GG,G
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic,117603679,ACCACT,TCAGA
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861,C,T
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129,T,G

In [73]:
clinvar.rename(columns = {"GRCh38Location" : "pos"}, inplace = True)

In [74]:
clinvar["Germline classification"].value_counts()

Germline classification
Pathogenic                             812
Likely pathogenic                      291
Pathogenic/Likely pathogenic           169
Benign                                  65
Benign/Likely benign                    32
Pathogenic; drug response               17
Pathogenic/Likely pathogenic; other      1
Name: count, dtype: int64

In [75]:
clinvar = clinvar[clinvar["Germline classification"].isin(["Pathogenic", "Benign", "Benign/Likely benign"])]

In [76]:
clinvar["Germline classification"].value_counts()

Germline classification
Pathogenic              812
Benign                   65
Benign/Likely benign     32
Name: count, dtype: int64

In [77]:
clinvar["cause"] = clinvar["Germline classification"].map({"Pathogenic" : 1, "Benign" : 0, "Benign/Likely benign": 0})

In [78]:
clinvar.head()

,Name,GRCh38Chromosome,pos,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos,ref,alt,cause
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226,TTTTTTTTT,TTTTTTTT,0
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898,GG,G,1
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861,C,T,1
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129,T,G,0
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,117480010,C,G,0

In [79]:
clinvar.to_csv("clinvar_cleaned.csv", index = False)

In [80]:
print(list(cftr2.columns), list(clinvar.columns))

['Variant cDNA name', 'variant determination', 'hgvs_genomic_grch38', 'chr', 'pos', 'ref', 'alt', 'cause'] ['Name', 'GRCh38Chromosome', 'pos', 'Canonical SPDI', 'dbSNP ID', 'Variant type', 'Germline classification', 'pos', 'ref', 'alt', 'cause']

In [81]:
cftr2.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,chr,pos,ref,alt,cause
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A,1
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7,117587778,G,T,1
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7,117587806,G,A,1
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7,117652877,C,G,1
5,c.3718-2477C>T,CF-causing,NC_000007.14:g.117639961C>T,7,117639961,C,T,1

In [82]:
clinvar.head()

,Name,GRCh38Chromosome,pos,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos,ref,alt,cause
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226,TTTTTTTTT,TTTTTTTT,0
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898,GG,G,1
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861,C,T,1
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129,T,G,0
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,117480010,C,G,0

In [83]:
clinvar = clinvar.iloc[:, [0, 1, 3, 4, 5, 6, 7, 8, 9, 10]]

In [84]:
clinvar.head()

,Name,GRCh38Chromosome,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos,ref,alt,cause
0,NC_000007.14:g.117479234del,7,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226,TTTTTTTTT,TTTTTTTT,0
1,NC_000007.14:g.117530899del,7,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898,GG,G,1
3,NC_000007.14:g.117675861C>T,7,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861,C,T,1
4,NG_016465.4:g.18346T>G,7,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129,T,G,0
5,NM_000492.3(CFTR):c.-85C>G,7,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,117480010,C,G,0

In [85]:
cftr2['chr'] = 'chr' + cftr2['chr'].astype(str)
clinvar['GRCh38Chromosome'] = 'chr' + clinvar['GRCh38Chromosome'].astype(str)
clinvar.rename(columns = {"GRCh38Chromosome" : "chr"}, inplace = True)

In [86]:
cftr2.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,chr,pos,ref,alt,cause
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1
5,c.3718-2477C>T,CF-causing,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1

In [87]:
clinvar.head()

,Name,chr,Canonical SPDI,dbSNP ID,Variant type,Germline classification,pos,ref,alt,cause
0,NC_000007.14:g.117479234del,chr7,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,117479226,TTTTTTTTT,TTTTTTTT,0
1,NC_000007.14:g.117530899del,chr7,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,117530898,GG,G,1
3,NC_000007.14:g.117675861C>T,chr7,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,117675861,C,T,1
4,NG_016465.4:g.18346T>G,chr7,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,117479129,T,G,0
5,NM_000492.3(CFTR):c.-85C>G,chr7,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,117480010,C,G,0

In [88]:
clinvar.to_csv("clinvar_cleaned.csv", index = False)

In [89]:
final_cftr_dataset = pd.concat([cftr2, clinvar], ignore_index = True)
final_cftr_dataset.drop_duplicates(subset = ["chr", "pos", "ref", "alt"], inplace = True)
final_cftr_dataset.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,chr,pos,ref,alt,cause,Name,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1,NaN,NaN,NaN,NaN,NaN
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1,NaN,NaN,NaN,NaN,NaN
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1,NaN,NaN,NaN,NaN,NaN
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1,NaN,NaN,NaN,NaN,NaN
4,c.3718-2477C>T,CF-causing,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1,NaN,NaN,NaN,NaN,NaN

In [90]:
final_cftr_dataset.shape

(1716, 13)

In [91]:
final_cftr_dataset.to_csv("final_cftr_dataset.csv", index = False)

In [92]:
conflicts = final_cftr_dataset.groupby(['chr', 'pos', 'ref', 'alt'])['cause'].nunique()
conflicts[conflicts > 1].index

MultiIndex([], names=['chr', 'pos', 'ref', 'alt'])