In [25]:
import pandas as pd

In [26]:
clinvar = pd.read_excel("clinvar_result_final_tabulated.xlsx")

# Load CFTR2 (multiple sheets)
cftr2_sheets = pd.read_excel("CFTR2_30January2026.xlsx", sheet_name=None)

sheet1 = cftr2_sheets[list(cftr2_sheets.keys())[0]]
sheet2 = cftr2_sheets[list(cftr2_sheets.keys())[1]]

print(clinvar.shape, sheet1.shape, sheet2.shape)

(1387, 25) (2099, 9) (2173, 13)

In [27]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.replace("\n", " ")
        .str.replace(r"\s+", " ", regex=True)
    )
    return df

sheet1 = clean_columns(sheet1)
sheet2 = clean_columns(sheet2)
clinvar = clean_columns(clinvar)

In [28]:
cftr2 = pd.merge(
    sheet1,
    sheet2,
    on="Variant cDNA name",
    how="inner"   # ensures only matched rows
)

In [29]:
print(cftr2.columns)

Index(['Variant legacy name_x', 'Variant protein name', 'Variant cDNA name',
       'Variant alternative names (other names that may have been used in the past)',
       '# alleles reported in CFTR2',
       'Allele frequency in CFTR2* (of 211106 identified alleles)',
       'Variant final determination 25 September 2024 (previous version)',
       'Variant final determination 30 January 2026 (current version)',
       'Change from previous?', 'Variant legacy name_y', 'Notes',
       'hgvs_genomic_grch37', 'hgvs_genomic_grch38', 'grch37_chr',
       'grch37_pos', 'grch37_ref', 'grch37_alt', 'grch38_chr', 'grch38_pos',
       'grch38_ref', 'grch38_alt'],
      dtype='object')

In [30]:
cftr2.head()

,Variant legacy name_x,Variant protein name,Variant cDNA name,Variant alternative names (other names that may have been used in the past),# alleles reported in CFTR2,Allele frequency in CFTR2* (of 211106 identified alleles),Variant final determination 25 September 2024 (previous version),Variant final determination 30 January 2026 (current version),Change from previous?,Variant legacy name_y,...,hgvs_genomic_grch37,hgvs_genomic_grch38,grch37_chr,grch37_pos,grch37_ref,grch37_alt,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,F508del,p.Phe508del,c.1521_1523del,"c.1521_1523del, 1653delCTT",137363,0.650683,CF-causing,CF-causing,No,F508del,...,NC_000007.13:g.117199646_117199648del,NC_000007.14:g.117559592_117559594del,7.0,117199644.0,ATCT,A,7.0,117559590.0,ATCT,A
1,G542X,p.Gly542X,c.1624G>T,1756G>T,5752,0.027247,CF-causing,CF-causing,No,G542X,...,NC_000007.13:g.117227832G>T,NC_000007.14:g.117587778G>T,7.0,117227832.0,G,T,7.0,117587778.0,G,T
2,G551D,p.Gly551Asp,c.1652G>A,1784G>A,3831,0.018147,CF-causing,CF-causing,No,G551D,...,NC_000007.13:g.117227860G>A,NC_000007.14:g.117587806G>A,7.0,117227860.0,G,A,7.0,117587806.0,G,A
3,N1303K,p.Asn1303Lys,c.3909C>G,4041C>G,3551,0.016821,CF-causing,CF-causing,No,N1303K,...,NC_000007.13:g.117292931C>G,NC_000007.14:g.117652877C>G,7.0,117292931.0,C,G,7.0,117652877.0,C,G
4,R117H,p.Arg117His,c.350G>A,482G>A,2262,0.010715,Varying clinical consequence,Varying clinical consequence,No,R117H,...,NC_000007.13:g.117171029G>A,NC_000007.14:g.117530975G>A,7.0,117171029.0,G,A,7.0,117530975.0,G,A

In [31]:
clinvar = clinvar[[
    "Name",
    "GRCh38Chromosome",
    "GRCh38Location",
    "Canonical SPDI",
    "dbSNP ID",
    "Variant type",
    "Molecular consequence",
    "Germline classification",
]]

cftr2 = cftr2[[
    "Variant cDNA name",
    "Variant final determination 30 January 2026 (current version)",
    "Variant cDNA name",
    "hgvs_genomic_grch38",
    "grch38_chr",
    "grch38_pos",
    "grch38_ref",
    "grch38_alt"
]]

In [32]:
clinvar.head(15)

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Molecular consequence,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,NaN,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,NaN,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,NaN,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,NaN,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,NaN,Benign
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,NaN,Benign
6,NM_000492.3(CFTR):c.1210-12T[9],7,117548628 - 117548629,NC_000007.14:117548628:TTTTTTT:TTTTTTTTT,rs1805177,Duplication,intron variant,Benign/Likely benign
7,NM_000492.3(CFTR):c.1521_1523del (p.Phe508del),7,117559591 - 117559593,NC_000007.14:117559590:TCTT:T,rs113993960,Deletion,inframe_deletion,Pathogenic
8,NM_000492.3(CFTR):c.2175dup (p.Glu726Argfs),7,117592340 - 117592341,NC_000007.14:117592340:AA:AAA,rs746418935,Duplication,frameshift variant,Pathogenic
9,NM_000492.3(CFTR):c.2909_2924dupGTGGGATTCTTAATAG,7,117606669 - 117606670,NC_000007.14:117606669:ATAGGTGGGATTCTTAATAG:AT...,NaN,Duplication,NaN,Pathogenic/Likely pathogenic
10,NM_000492.3(CFTR):c.2909delG,7,117606673,NC_000007.14:117606672:GG:G,rs397508458,Deletion,NaN,Pathogenic
11,NM_000492.3(CFTR):c.3468+2dup,7,117614714 - 117614715,NC_000007.14:117614714:T:TT,rs1554392800,Duplication,splice donor variant,Pathogenic
12,NM_000492.3(CFTR):c.3718-2477C>T,7,117639961,NC_000007.14:117639960:C:T,rs75039782,single nucleotide variant,intron variant,Pathogenic
13,NM_000492.3(CFTR):c.3965_3969dup,7,117664686 - 117664687,NC_000007.14:117664686:GGTTGGG:GGTTGGGTTGGG,rs1209386423,Duplication,NaN,Pathogenic
14,NM_000492.3(CFTR):c.[1075C>A;1079C>A],7|7,117540305,NC_000007.14:117540304:C:A|NC_000007.14:117540...,rs76879328|rs75053309,Haplotype,missense variant,Pathogenic

In [33]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),Variant cDNA name,hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,c.1521_1523del,NC_000007.14:g.117559592_117559594del,7.0,117559590.0,ATCT,A
1,c.1624G>T,CF-causing,c.1624G>T,NC_000007.14:g.117587778G>T,7.0,117587778.0,G,T
2,c.1652G>A,CF-causing,c.1652G>A,NC_000007.14:g.117587806G>A,7.0,117587806.0,G,A
3,c.3909C>G,CF-causing,c.3909C>G,NC_000007.14:g.117652877C>G,7.0,117652877.0,C,G
4,c.350G>A,Varying clinical consequence,c.350G>A,NC_000007.14:g.117530975G>A,7.0,117530975.0,G,A

In [34]:
clinvar.drop(columns=["Molecular consequence"], axis = 1, inplace = True)

In [35]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign

In [36]:
cftr2.dtypes

Variant cDNA name                                                 object
Variant final determination 30 January 2026 (current version)     object
Variant cDNA name                                                 object
hgvs_genomic_grch38                                               object
grch38_chr                                                       float64
grch38_pos                                                       float64
grch38_ref                                                        object
grch38_alt                                                        object
dtype: object

In [37]:
clinvar.dtypes

Name                       object
GRCh38Chromosome           object
GRCh38Location             object
Canonical SPDI             object
dbSNP ID                   object
Variant type               object
Germline classification    object
dtype: object

In [ ]:
clinvar["GRCh38Chromosome"] = clinvar["GRCh38Chromosome"].astype(int)

ValueError: invalid literal for int() with base 10: '7|7'