In [1]:
import pandas as pd

In [ ]:
clinvar = pd.read_excel("datasets/clinvar_result_final_tabulated.xlsx")

# Load CFTR2 (multiple sheets)
cftr2_sheets = pd.read_excel("datasets/CFTR2_30January2026.xlsx", sheet_name=None)

sheet1 = cftr2_sheets[list(cftr2_sheets.keys())[0]]
sheet2 = cftr2_sheets[list(cftr2_sheets.keys())[1]]

print(clinvar.shape, sheet1.shape, sheet2.shape)

(1387, 25) (2099, 9) (2173, 13)

In [3]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip()
        .str.replace("\n", " ")
        .str.replace(r"\s+", " ", regex=True)
    )
    return df

sheet1 = clean_columns(sheet1)
sheet2 = clean_columns(sheet2)
clinvar = clean_columns(clinvar)

In [4]:
cftr2 = pd.merge(
    sheet1,
    sheet2,
    on="Variant cDNA name",
    how="inner"   # ensures only matched rows
)

In [5]:
print(cftr2.columns)

Index(['Variant legacy name_x', 'Variant protein name', 'Variant cDNA name',
       'Variant alternative names (other names that may have been used in the past)',
       '# alleles reported in CFTR2',
       'Allele frequency in CFTR2* (of 211106 identified alleles)',
       'Variant final determination 25 September 2024 (previous version)',
       'Variant final determination 30 January 2026 (current version)',
       'Change from previous?', 'Variant legacy name_y', 'Notes',
       'hgvs_genomic_grch37', 'hgvs_genomic_grch38', 'grch37_chr',
       'grch37_pos', 'grch37_ref', 'grch37_alt', 'grch38_chr', 'grch38_pos',
       'grch38_ref', 'grch38_alt'],
      dtype='object')

In [6]:
cftr2.head()

,Variant legacy name_x,Variant protein name,Variant cDNA name,Variant alternative names (other names that may have been used in the past),# alleles reported in CFTR2,Allele frequency in CFTR2* (of 211106 identified alleles),Variant final determination 25 September 2024 (previous version),Variant final determination 30 January 2026 (current version),Change from previous?,Variant legacy name_y,...,hgvs_genomic_grch37,hgvs_genomic_grch38,grch37_chr,grch37_pos,grch37_ref,grch37_alt,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,F508del,p.Phe508del,c.1521_1523del,"c.1521_1523del, 1653delCTT",137363,0.650683,CF-causing,CF-causing,No,F508del,...,NC_000007.13:g.117199646_117199648del,NC_000007.14:g.117559592_117559594del,7.0,117199644.0,ATCT,A,7.0,117559590.0,ATCT,A
1,G542X,p.Gly542X,c.1624G>T,1756G>T,5752,0.027247,CF-causing,CF-causing,No,G542X,...,NC_000007.13:g.117227832G>T,NC_000007.14:g.117587778G>T,7.0,117227832.0,G,T,7.0,117587778.0,G,T
2,G551D,p.Gly551Asp,c.1652G>A,1784G>A,3831,0.018147,CF-causing,CF-causing,No,G551D,...,NC_000007.13:g.117227860G>A,NC_000007.14:g.117587806G>A,7.0,117227860.0,G,A,7.0,117587806.0,G,A
3,N1303K,p.Asn1303Lys,c.3909C>G,4041C>G,3551,0.016821,CF-causing,CF-causing,No,N1303K,...,NC_000007.13:g.117292931C>G,NC_000007.14:g.117652877C>G,7.0,117292931.0,C,G,7.0,117652877.0,C,G
4,R117H,p.Arg117His,c.350G>A,482G>A,2262,0.010715,Varying clinical consequence,Varying clinical consequence,No,R117H,...,NC_000007.13:g.117171029G>A,NC_000007.14:g.117530975G>A,7.0,117171029.0,G,A,7.0,117530975.0,G,A

In [7]:
clinvar = clinvar[[
    "Name",
    "GRCh38Chromosome",
    "GRCh38Location",
    "Canonical SPDI",
    "dbSNP ID",
    "Variant type",
    "Molecular consequence",
    "Germline classification",
]]

cftr2 = cftr2[[
    "Variant cDNA name",
    "Variant final determination 30 January 2026 (current version)",
    "hgvs_genomic_grch38",
    "grch38_chr",
    "grch38_pos",
    "grch38_ref",
    "grch38_alt"
]]

In [8]:
clinvar.head(15)

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Molecular consequence,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,NaN,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,NaN,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,NaN,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,NaN,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,NaN,Benign
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,NaN,Benign
6,NM_000492.3(CFTR):c.1210-12T[9],7,117548628 - 117548629,NC_000007.14:117548628:TTTTTTT:TTTTTTTTT,rs1805177,Duplication,intron variant,Benign/Likely benign
7,NM_000492.3(CFTR):c.1521_1523del (p.Phe508del),7,117559591 - 117559593,NC_000007.14:117559590:TCTT:T,rs113993960,Deletion,inframe_deletion,Pathogenic
8,NM_000492.3(CFTR):c.2175dup (p.Glu726Argfs),7,117592340 - 117592341,NC_000007.14:117592340:AA:AAA,rs746418935,Duplication,frameshift variant,Pathogenic
9,NM_000492.3(CFTR):c.2909_2924dupGTGGGATTCTTAATAG,7,117606669 - 117606670,NC_000007.14:117606669:ATAGGTGGGATTCTTAATAG:AT...,NaN,Duplication,NaN,Pathogenic/Likely pathogenic
10,NM_000492.3(CFTR):c.2909delG,7,117606673,NC_000007.14:117606672:GG:G,rs397508458,Deletion,NaN,Pathogenic
11,NM_000492.3(CFTR):c.3468+2dup,7,117614714 - 117614715,NC_000007.14:117614714:T:TT,rs1554392800,Duplication,splice donor variant,Pathogenic
12,NM_000492.3(CFTR):c.3718-2477C>T,7,117639961,NC_000007.14:117639960:C:T,rs75039782,single nucleotide variant,intron variant,Pathogenic
13,NM_000492.3(CFTR):c.3965_3969dup,7,117664686 - 117664687,NC_000007.14:117664686:GGTTGGG:GGTTGGGTTGGG,rs1209386423,Duplication,NaN,Pathogenic
14,NM_000492.3(CFTR):c.[1075C>A;1079C>A],7|7,117540305,NC_000007.14:117540304:C:A|NC_000007.14:117540...,rs76879328|rs75053309,Haplotype,missense variant,Pathogenic

In [9]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7.0,117559590.0,ATCT,A
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7.0,117587778.0,G,T
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7.0,117587806.0,G,A
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7.0,117652877.0,C,G
4,c.350G>A,Varying clinical consequence,NC_000007.14:g.117530975G>A,7.0,117530975.0,G,A

In [10]:
clinvar.drop(columns=["Molecular consequence"], axis = 1, inplace = True)

In [11]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign

In [12]:
cftr2.dtypes

Variant cDNA name                                                 object
Variant final determination 30 January 2026 (current version)     object
hgvs_genomic_grch38                                               object
grch38_chr                                                       float64
grch38_pos                                                       float64
grch38_ref                                                        object
grch38_alt                                                        object
dtype: object

In [13]:
clinvar.dtypes

Name                       object
GRCh38Chromosome           object
GRCh38Location             object
Canonical SPDI             object
dbSNP ID                   object
Variant type               object
Germline classification    object
dtype: object

In [14]:
cftr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2026 entries, 0 to 2025
Data columns (total 7 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Variant cDNA name                                              2026 non-null   object
 1   Variant final determination 30 January 2026 (current version)  2026 non-null   object
 2   hgvs_genomic_grch38                                            1823 non-null   object
 3   grch38_chr                                                     1823 non-null   float64
 4   grch38_pos                                                     1823 non-null   float64
 5   grch38_ref                                                     1823 non-null   object
 6   grch38_alt                                                     1823 non-null   object
dtypes: float64(2), object(5)
memory usage: 110.9+ KB

In [15]:
cftr2 = cftr2.dropna(
    subset=[
        "hgvs_genomic_grch38",
        "grch38_chr",
        "grch38_pos",
        "grch38_ref",
        "grch38_alt"
    ]
)

In [16]:
cftr2["grch38_chr"] = pd.to_numeric(cftr2["grch38_chr"], errors="coerce")
cftr2["grch38_pos"] = pd.to_numeric(cftr2["grch38_pos"], errors="coerce")

cftr2 = cftr2.dropna(subset=["grch38_chr", "grch38_pos"])

cftr2["grch38_chr"] = cftr2["grch38_chr"].astype(int)
cftr2["grch38_pos"] = cftr2["grch38_pos"].astype(int)

In [17]:
cftr2.head()

,Variant cDNA name,Variant final determination 30 January 2026 (current version),hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7,117587778,G,T
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7,117587806,G,A
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7,117652877,C,G
4,c.350G>A,Varying clinical consequence,NC_000007.14:g.117530975G>A,7,117530975,G,A

In [18]:
cftr2["Variant final determination 30 January 2026 (current version)"].value_counts()

Variant final determination 30 January 2026 (current version)
CF-causing                      1091
No interpretation available      617
Varying clinical consequence      78
Non CF-causing                    37
Name: count, dtype: int64

In [19]:
cftr2.rename(columns = {"Variant final determination 30 January 2026 (current version)" : "variant determination"}, inplace = True)

In [20]:
cftr2.head()

,Variant cDNA name,variant determination,hgvs_genomic_grch38,grch38_chr,grch38_pos,grch38_ref,grch38_alt
0,c.1521_1523del,CF-causing,NC_000007.14:g.117559592_117559594del,7,117559590,ATCT,A
1,c.1624G>T,CF-causing,NC_000007.14:g.117587778G>T,7,117587778,G,T
2,c.1652G>A,CF-causing,NC_000007.14:g.117587806G>A,7,117587806,G,A
3,c.3909C>G,CF-causing,NC_000007.14:g.117652877C>G,7,117652877,C,G
4,c.350G>A,Varying clinical consequence,NC_000007.14:g.117530975G>A,7,117530975,G,A

In [21]:
cftr2 = cftr2[cftr2["variant determination"].isin(["CF-causing", "Non CF-causing"])]

In [22]:
cftr2["cause"] = cftr2["variant determination"].map({"CF-causing" : 1, "Non CF-causing" : 0})

In [23]:
cftr2["cause"].value_counts()

cause
1    1091
0      37
Name: count, dtype: int64

In [24]:
cftr2 = cftr2.rename(
    columns={
        "grch38_chr": "chr",
        "grch38_pos": "pos",
        "grch38_ref": "ref",
        "grch38_alt": "alt"
    }
)

# Standardize
cftr2["chr"] = "chr" + cftr2["chr"].astype(str)
cftr2["ref"] = cftr2["ref"].astype(str).str.upper()
cftr2["alt"] = cftr2["alt"].astype(str).str.upper()

cftr2 = cftr2[
    ["Variant cDNA name", "hgvs_genomic_grch38", "chr", "pos", "ref", "alt", "cause"]
]

In [25]:
cftr2.head()

,Variant cDNA name,hgvs_genomic_grch38,chr,pos,ref,alt,cause
0,c.1521_1523del,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1
1,c.1624G>T,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1
2,c.1652G>A,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1
3,c.3909C>G,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1
5,c.3718-2477C>T,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1

In [26]:
import re

def extract_hgvs_pos(hgvs):
    match = re.search(r"g\.(\d+)", str(hgvs))
    return int(match.group(1)) if match else None

cftr2["hgvs_pos"] = cftr2["hgvs_genomic_grch38"].apply(extract_hgvs_pos)

In [27]:
cftr2["pos_diff"] = cftr2["hgvs_pos"] - cftr2["pos"]

print(cftr2["pos_diff"].value_counts().head(10))

pos_diff
0    664
1    184
2    117
3     72
4     39
5     23
6     21
7      7
9      1
Name: count, dtype: int64

In [28]:
cftr2.head()

,Variant cDNA name,hgvs_genomic_grch38,chr,pos,ref,alt,cause,hgvs_pos,pos_diff
0,c.1521_1523del,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1,117559592,2
1,c.1624G>T,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1,117587778,0
2,c.1652G>A,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1,117587806,0
3,c.3909C>G,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1,117652877,0
5,c.3718-2477C>T,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1,117639961,0

In [29]:
cftr2.drop(columns=["hgvs_pos", "pos_diff"], inplace=True)

In [30]:
cftr2.head()

,Variant cDNA name,hgvs_genomic_grch38,chr,pos,ref,alt,cause
0,c.1521_1523del,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1
1,c.1624G>T,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1
2,c.1652G>A,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1
3,c.3909C>G,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1
5,c.3718-2477C>T,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1

In [ ]:
from pyfaidx import Fasta

genome = Fasta(r"Homo_sapiens_CFTR_sequence.fa")
print(list(genome.keys()))
#print(len(genome["7"]))

['NC_000001.11', 'NT_187361.1', 'NT_187362.1', 'NT_187363.1', 'NT_187364.1', 'NT_187365.1', 'NT_187366.1', 'NT_187367.1', 'NT_187368.1', 'NT_187369.1', 'NC_000002.12', 'NT_187370.1', 'NT_187371.1', 'NC_000003.12', 'NT_167215.1', 'NC_000004.12', 'NT_113793.3', 'NC_000005.10', 'NT_113948.1', 'NC_000006.12', 'NC_000007.14', 'NC_000008.11', 'NC_000009.12', 'NT_187372.1', 'NT_187373.1', 'NT_187374.1', 'NT_187375.1', 'NC_000010.11', 'NC_000011.10', 'NC_000012.12', 'NC_000013.11', 'NC_000014.9', 'NT_113796.3', 'NT_167219.1', 'NT_187377.1', 'NT_113888.1', 'NT_187378.1', 'NT_187379.1', 'NT_187380.1', 'NT_187381.1', 'NC_000015.10', 'NT_187382.1', 'NC_000016.10', 'NT_187383.1', 'NC_000017.11', 'NT_113930.2', 'NT_187384.1', 'NT_187385.1', 'NC_000018.10', 'NC_000019.10', 'NC_000020.11', 'NC_000021.9', 'NC_000022.11', 'NT_187386.1', 'NT_187387.1', 'NT_187388.1', 'NT_187390.1', 'NT_187391.1', 'NT_187392.1', 'NT_187393.1', 'NT_187394.1', 'NC_000023.11', 'NC_000024.10', 'NT_187395.1', 'NT_187396.1', 'NT_187397.1', 'NT_187398.1', 'NT_187399.1', 'NT_187400.1', 'NT_187401.1', 'NT_187402.1', 'NT_187403.1', 'NT_187404.1', 'NT_187405.1', 'NT_187406.1', 'NT_187407.1', 'NT_187408.1', 'NT_187409.1', 'NT_187410.1', 'NT_187411.1', 'NT_187412.1', 'NT_187413.1', 'NT_187414.1', 'NT_187415.1', 'NT_187416.1', 'NT_187417.1', 'NT_187418.1', 'NT_187419.1', 'NT_187420.1', 'NT_187421.1', 'NT_187422.1', 'NT_187423.1', 'NT_187424.1', 'NT_187425.1', 'NT_187426.1', 'NT_187427.1', 'NT_187428.1', 'NT_187429.1', 'NT_187430.1', 'NT_187431.1', 'NT_187432.1', 'NT_187433.1', 'NT_187434.1', 'NT_187435.1', 'NT_187436.1', 'NT_187437.1', 'NT_187438.1', 'NT_187439.1', 'NT_187440.1', 'NT_187441.1', 'NT_187442.1', 'NT_187443.1', 'NT_187444.1', 'NT_187445.1', 'NT_187446.1', 'NT_187447.1', 'NT_187448.1', 'NT_187449.1', 'NT_187450.1', 'NT_187451.1', 'NT_187452.1', 'NT_187453.1', 'NT_187454.1', 'NT_187455.1', 'NT_187456.1', 'NT_187457.1', 'NT_187458.1', 'NT_187459.1', 'NT_187460.1', 'NT_187461.1', 'NT_187462.1', 'NT_187463.1', 'NT_187464.1', 'NT_187465.1', 'NT_187466.1', 'NT_187467.1', 'NT_187468.1', 'NT_187469.1', 'NT_187470.1', 'NT_187471.1', 'NT_187472.1', 'NT_187473.1', 'NT_187474.1', 'NT_187475.1', 'NT_187476.1', 'NT_187477.1', 'NT_187478.1', 'NT_187479.1', 'NT_187480.1', 'NT_187481.1', 'NT_187482.1', 'NT_187483.1', 'NT_187484.1', 'NT_187485.1', 'NT_187486.1', 'NT_187487.1', 'NT_187488.1', 'NT_187489.1', 'NT_187490.1', 'NT_187491.1', 'NT_187492.1', 'NT_187493.1', 'NT_187494.1', 'NT_187495.1', 'NT_187496.1', 'NT_113901.1', 'NT_167213.1', 'NT_167214.1', 'NT_167218.1', 'NT_187497.1', 'NT_167220.1', 'NT_167208.1', 'NT_187498.1', 'NT_187499.1', 'NT_187500.1', 'NT_187501.1', 'NT_187502.1', 'NT_187503.1', 'NT_187504.1', 'NT_187505.1', 'NT_187506.1', 'NT_187508.1', 'NT_187509.1', 'NT_187510.1', 'NT_187511.1', 'NT_187512.1', 'NT_167209.1', 'NT_187513.1', 'NT_167211.2', 'NT_113889.1', 'NW_012132914.1', 'NW_015495298.1', 'NW_025791756.1', 'NW_011332688.1', 'NW_014040926.1', 'NW_009646195.1', 'NW_018654706.1', 'NW_019805487.1', 'NW_009646194.1', 'NW_018654707.1', 'NW_014040925.1', 'NW_017852928.1', 'NW_009646196.1', 'NW_025791753.1', 'NW_025791758.1', 'NW_025791759.1', 'NW_025791754.1', 'NW_011332687.1', 'NW_018654708.1', 'NW_014040927.1', 'NW_025791757.1', 'NW_025791755.1', 'NW_021159988.1', 'NW_025791767.1', 'NW_025791768.1', 'NW_025791766.1', 'NW_025791763.1', 'NW_012132915.1', 'NW_025791760.1', 'NW_025791765.1', 'NW_018654709.1', 'NW_025791762.1', 'NW_025791761.1', 'NW_025791764.1', 'NW_015495299.1', 'NW_018654710.1', 'NW_011332690.1', 'NW_021159987.1', 'NW_011332689.1', 'NW_017363813.1', 'NW_025791770.1', 'NW_025791771.1', 'NW_009646197.1', 'NW_012132916.1', 'NW_011332691.1', 'NW_021159989.1', 'NW_018654711.1', 'NW_012132917.1', 'NW_009646198.1', 'NW_019805491.1', 'NW_019805492.1', 'NW_019805490.1', 'NW_019805489.1', 'NW_019805488.1', 'NW_025791769.1', 'NW_021159990.1', 'NW_021159993.1', 'NW_013171799.1', 'NW_025791774.1', 'NW_021159992.1', 'NW_021159994.1', 'NW_021159991.1', 'NW_021159995.1', 'NW_013171800.1', 'NW_013171801.1', 'NW_025791772.1', 'NW_017363814.1', 'NW_025791773.1', 'NW_015495301.1', 'NW_015495300.1', 'NW_025791777.1', 'NW_018654712.1', 'NW_025791776.1', 'NW_009646199.1', 'NW_016107297.1', 'NW_025791779.1', 'NW_021159996.1', 'NW_025791778.1', 'NW_016107298.1', 'NW_025791775.1', 'NW_018654713.1', 'NW_013171803.1', 'NW_025791780.1', 'NW_012132918.1', 'NW_009646200.1', 'NW_013171802.1', 'NW_017363815.1', 'NW_021159997.1', 'NW_021159998.1', 'NW_019805493.1', 'NW_025791781.1', 'NW_017852929.1', 'NW_017852930.1', 'NW_018654714.1', 'NW_018654715.1', 'NW_012132919.1', 'NW_025791785.1', 'NW_018654717.1', 'NW_017852932.1', 'NW_025791782.1', 'NW_017852931.1', 'NW_025791784.1', 'NW_019805494.1', 'NW_025791786.1', 'NW_018654716.1', 'NW_025791783.1', 'NW_013171804.1', 'NW_013171805.1', 'NW_025791789.1', 'NW_025791787.1', 'NW_025791788.1', 'NW_009646201.1', 'NW_021159999.1', 'NW_021160000.1', 'NW_011332694.1', 'NW_021160001.1', 'NW_013171806.1', 'NW_009646202.1', 'NW_013171807.1', 'NW_025791790.1', 'NW_011332693.1', 'NW_011332692.1', 'NW_015148966.2', 'NW_025791792.1', 'NW_021160004.1', 'NW_025791794.1', 'NW_011332695.1', 'NW_021160006.1', 'NW_019805496.1', 'NW_019805495.1', 'NW_017363816.1', 'NW_025791793.1', 'NW_019805498.1', 'NW_021160005.1', 'NW_021160003.1', 'NW_019805497.1', 'NW_013171808.1', 'NW_021160002.1', 'NW_025791791.1', 'NW_009646203.1', 'NW_013171809.1', 'NW_018654718.1', 'NW_021160008.1', 'NW_011332696.1', 'NW_009646204.1', 'NW_025791795.1', 'NW_018654720.1', 'NW_015148967.1', 'NW_018654719.1', 'NW_011332697.1', 'NW_019805499.1', 'NW_021160007.1', 'NW_021160012.1', 'NW_011332699.1', 'NW_013171810.1', 'NW_021160009.1', 'NW_009646205.1', 'NW_011332700.1', 'NW_013171811.1', 'NW_021160010.1', 'NW_021160011.1', 'NW_011332698.1', 'NW_021160013.1', 'NW_025791796.1', 'NW_018654722.1', 'NW_021160014.1', 'NW_018654721.1', 'NW_011332701.1', 'NW_021160018.1', 'NW_021160017.1', 'NW_012132920.1', 'NW_025791798.1', 'NW_021160016.1', 'NW_025791797.1', 'NW_021160015.1', 'NW_025791799.1', 'NW_013171812.1', 'NW_019805500.1', 'NW_017852933.1', 'NW_021160019.1', 'NW_013171813.1', 'NW_018654723.1', 'NW_012132921.1', 'NW_025791800.1', 'NW_017363817.1', 'NW_021160020.1', 'NW_016107299.1', 'NW_017363819.1', 'NW_025791803.1', 'NW_025791801.1', 'NW_017363818.1', 'NW_019805501.1', 'NW_025791806.1', 'NW_025791802.1', 'NW_025791805.1', 'NW_021160021.1', 'NW_025791804.1', 'NW_019805503.1', 'NW_014040928.1', 'NW_019805502.1', 'NW_013171814.1', 'NW_018654724.1', 'NW_025791809.1', 'NW_025791810.1', 'NW_025791807.1', 'NW_021160022.1', 'NW_014040929.1', 'NW_025791808.1', 'NW_009646206.1', 'NW_016107300.1', 'NW_016107301.1', 'NW_016107302.1', 'NW_016107303.1', 'NW_016107304.1', 'NW_016107305.1', 'NW_016107306.1', 'NW_016107307.1', 'NW_016107308.1', 'NW_016107309.1', 'NW_016107310.1', 'NW_016107311.1', 'NW_016107313.1', 'NW_016107314.1', 'NW_016107312.1', 'NW_025791811.1', 'NW_025791812.1', 'NW_021160023.1', 'NW_025791813.1', 'NW_025791814.1', 'NW_025791815.1', 'NW_021160026.1', 'NW_021160024.1', 'NW_009646207.1', 'NW_014040930.1', 'NW_014040931.1', 'NW_009646208.1', 'NW_015148968.1', 'NW_021160025.1', 'NW_015148969.2', 'NW_017363820.1', 'NW_021160031.1', 'NW_025791820.1', 'NW_021160028.1', 'NW_025791816.1', 'NW_021160029.1', 'NW_025791817.1', 'NW_021160027.1', 'NW_025791819.1', 'NW_021160030.1', 'NW_025791818.1', 'NW_018654725.1', 'NW_025791821.1', 'NW_018654726.1', 'NW_009646209.1', 'NT_187515.1', 'NT_187517.1', 'NT_187514.1', 'NT_187520.1', 'NW_003315905.1', 'NW_003315906.1', 'NW_003315907.2', 'NT_187521.1', 'NT_187519.1', 'NT_187516.1', 'NT_187518.1', 'NT_187525.1', 'NT_187526.1', 'NT_187529.1', 'NT_187522.1', 'NW_003315908.1', 'NT_187524.1', 'NT_187531.1', 'NT_187530.1', 'NT_187528.1', 'NW_003571033.2', 'NW_003315909.1', 'NT_187527.1', 'NT_187523.1', 'NW_003871060.2', 'NT_187535.1', 'NT_187537.1', 'NW_003315913.1', 'NT_187533.1', 'NT_187536.1', 'NT_187538.1', 'NT_187532.1', 'NT_187534.1', 'NT_187539.1', 'NT_187540.1', 'NW_003315915.1', 'NT_187541.1', 'NT_167250.2', 'NT_187544.1', 'NW_003315914.1', 'NT_187542.1', 'NT_187545.1', 'NT_187543.1', 'NT_187550.1', 'NT_187548.1', 'NT_187547.1', 'NW_003315920.1', 'NW_003571036.1', 'NT_187551.1', 'NW_003315917.2', 'NW_003315918.1', 'NT_187549.1', 'NW_003315919.1', 'NT_187546.1', 'NT_167244.2', 'NT_187555.1', 'NT_187554.1', 'NW_003315921.1', 'NT_187556.1', 'NT_187557.1', 'NW_004166862.2', 'NT_187552.1', 'NT_187553.1', 'NT_187558.1', 'NT_187561.1', 'NT_187559.1', 'NW_003315922.2', 'NT_187562.1', 'NT_187564.1', 'NT_187563.1', 'NT_187560.1', 'NT_187572.1', 'NT_187568.1', 'NT_187565.1', 'NT_187576.1', 'NT_187570.1', 'NT_187577.1', 'NT_187566.1', 'NT_187567.1', 'NT_187574.1', 'NT_187575.1', 'NT_187573.1', 'NT_187571.1', 'NT_187569.1', 'NW_003315928.1', 'NW_003315929.1', 'NW_003315930.1', 'NW_003315931.1', 'NT_187578.1', 'NW_003315934.1', 'NT_187579.1', 'NW_003315935.1', 'NT_187586.1', 'NT_187584.1', 'NT_187585.1', 'NT_187583.1', 'NW_003315936.1', 'NW_003871073.1', 'NW_003871074.1', 'NT_187582.1', 'NT_187581.1', 'NW_003571049.1', 'NW_003571050.1', 'NT_187588.1', 'NW_003315938.1', 'NT_187587.1', 'NW_003315939.2', 'NW_003315941.1', 'NW_003315942.2', 'NT_187590.1', 'NW_003315940.1', 'NT_187589.1', 'NT_187591.1', 'NT_187594.1', 'NT_187593.1', 'NT_187597.1', 'NT_187595.1', 'NT_187592.1', 'NT_187596.1', 'NT_187598.1', 'NT_187601.1', 'NT_187599.1', 'NT_187600.1', 'NT_187602.1', 'NT_187604.1', 'NT_187603.1', 'NW_003315943.1', 'NT_187605.1', 'NW_003315944.2', 'NT_187606.1', 'NT_187610.1', 'NT_187609.1', 'NT_187608.1', 'NT_187607.1', 'NW_003315945.1', 'NW_003315946.1', 'NW_003315952.3', 'NT_187613.1', 'NT_187611.1', 'NT_187614.1', 'NW_003871091.1', 'NW_003871092.1', 'NW_003315953.2', 'NT_167251.2', 'NW_003315954.1', 'NT_187615.1', 'NT_187616.1', 'NW_003315955.1', 'NT_187612.1', 'NT_187618.1', 'NW_003315956.1', 'NW_003315959.1', 'NW_003315960.1', 'NW_003315957.1', 'NW_003315958.1', 'NW_003315961.1', 'NT_187617.1', 'NT_187622.1', 'NT_187621.1', 'NW_003315962.1', 'NW_003315964.2', 'NW_003315965.1', 'NW_003315963.1', 'NT_187619.1', 'NT_187620.1', 'NW_003571054.1', 'NW_003315966.2', 'NT_187623.1', 'NT_187625.1', 'NT_187624.1', 'NW_003315967.2', 'NT_187628.1', 'NT_187627.1', 'NW_003315968.2', 'NW_003315969.2', 'NW_003315970.2', 'NT_187626.1', 'NT_187629.1', 'NT_187632.1', 'NT_187633.1', 'NT_187630.1', 'NT_187631.1', 'NW_003315972.2', 'NW_003315971.2', 'NT_187634.1', 'NT_187635.1', 'NT_187646.1', 'NT_187648.1', 'NT_187647.1', 'NT_187649.1', 'NT_187650.1', 'NT_187651.1', 'NT_187652.1', 'NT_113891.3', 'NT_187653.1', 'NT_187655.1', 'NT_187654.1', 'NT_187656.1', 'NT_187657.1', 'NT_187658.1', 'NT_187659.1', 'NT_187660.1', 'NT_187662.1', 'NT_187664.1', 'NT_187661.1', 'NW_003871093.1', 'NT_187663.1', 'NT_187665.1', 'NT_187666.1', 'NW_003571055.2', 'NW_004504305.1', 'NT_187667.1', 'NT_187678.1', 'NT_187679.1', 'NT_167245.2', 'NT_187680.1', 'NT_187681.1', 'NW_003571056.2', 'NT_187682.1', 'NT_187688.1', 'NT_167246.2', 'NW_003571057.2', 'NT_187689.1', 'NT_167247.2', 'NW_003571058.2', 'NT_187690.1', 'NT_167248.2', 'NW_003571059.2', 'NT_187691.1', 'NT_167249.2', 'NW_003571060.1', 'NT_187692.1', 'NW_003571061.2', 'NT_187693.1', 'NT_187636.1', 'NT_187637.1', 'NT_187638.1', 'NT_187639.1', 'NT_187640.1', 'NT_187641.1', 'NT_187642.1', 'NT_187643.1', 'NT_187644.1', 'NT_187645.1', 'NT_187668.1', 'NT_187669.1', 'NT_187670.1', 'NT_187671.1', 'NT_187672.1', 'NT_187673.1', 'NT_187674.1', 'NT_187675.1', 'NT_187676.1', 'NT_187677.1', 'NT_187683.1', 'NT_187684.1', 'NT_187685.1', 'NT_187686.1', 'NT_187687.1', 'NT_113949.2', 'NC_012920.1']

In [32]:
for i, row in cftr2.sample(10).iterrows():
    chrom = row["hgvs_genomic_grch38"].split(":")[0]
    pos = int(row["pos"])
    ref = str(row["ref"]).upper()

    genome_ref = str(genome[chrom][pos-1:pos-1+len(ref)]).upper()

    print("REF:    ", ref)
    print("GENOME: ", genome_ref)
    print("MATCH:  ", ref == genome_ref)
    print("-"*50)

REF:     G
GENOME:  G
MATCH:   True
--------------------------------------------------
REF:     CTT
GENOME:  CTT
MATCH:   True
--------------------------------------------------
REF:     G
GENOME:  G
MATCH:   True
--------------------------------------------------
REF:     C
GENOME:  C
MATCH:   True
--------------------------------------------------
REF:     G
GENOME:  G
MATCH:   True
--------------------------------------------------
REF:     T
GENOME:  T
MATCH:   True
--------------------------------------------------
REF:     T
GENOME:  T
MATCH:   True
--------------------------------------------------
REF:     G
GENOME:  G
MATCH:   True
--------------------------------------------------
REF:     G
GENOME:  G
MATCH:   True
--------------------------------------------------
REF:     T
GENOME:  T
MATCH:   True
--------------------------------------------------

In [33]:
matches = []
failed_examples = []

for _, row in cftr2.iterrows():
    try:
        # Extract chromosome from HGVS (correct for GCF genome)
        chrom = str(row["hgvs_genomic_grch38"]).split(":")[0]
        
        pos = int(row["pos"])
        ref = str(row["ref"]).upper()

        # Get genome sequence (convert to uppercase)
        genome_ref = str(genome[chrom][pos-1:pos-1+len(ref)]).upper()

        match = (ref == genome_ref)
        matches.append(match)

        # store a few failures for debugging
        if not match and len(failed_examples) < 5:
            failed_examples.append((ref, genome_ref, chrom, pos))

    except Exception as e:
        matches.append(False)
        if len(failed_examples) < 5:
            failed_examples.append(("ERROR", str(e)))

# Results
match_rate = sum(matches) / len(matches)

print(f"Total variants: {len(matches)}")
print(f"Match rate: {match_rate:.4f}")
print(f"Matched: {sum(matches)}")
print(f"Failed: {len(matches) - sum(matches)}")

print("\nSample mismatches:")
for ex in failed_examples:
    print(ex)

Total variants: 1128
Match rate: 1.0000
Matched: 1128
Failed: 0

Sample mismatches:

In [34]:
cftr2["cause"].value_counts()

cause
1    1091
0      37
Name: count, dtype: int64

In [ ]:
cftr2.to_csv("cleaned_datasets/cftr2_cleaned.csv", index = False)

In [36]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign

In [37]:
clinvar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1387 entries, 0 to 1386
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     1387 non-null   object
 1   GRCh38Chromosome         1387 non-null   object
 2   GRCh38Location           1387 non-null   object
 3   Canonical SPDI           1387 non-null   object
 4   dbSNP ID                 1262 non-null   object
 5   Variant type             1387 non-null   object
 6   Germline classification  1387 non-null   object
dtypes: object(7)
memory usage: 76.0+ KB

In [38]:
clinvar["GRCh38Chromosome"] = 7

In [39]:
def parse_spdi(spdi):
    try:
        seq_id, pos0, ref, alt = str(spdi).split(":", 3)
        return pd.Series([seq_id, int(pos0), ref, alt])
    except:
        return pd.Series([None, None, None, None])

In [40]:
clinvar[["chr", "spdi_pos0", "ref", "alt"]] = clinvar["Canonical SPDI"].apply(parse_spdi)

In [75]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,chr,spdi_pos0,ref,alt
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,NC_000007.14,117479225,TTTTTTTTT,TTTTTTTT
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,NC_000007.14,117530897,GG,G
2,NC_000007.14:g.117603679_117603684delinsTCAGA,7,117603679 - 117603684,NC_000007.14:117603678:ACCACT:TCAGA,rs1554391033,Indel,Pathogenic/Likely pathogenic,NC_000007.14,117603678,ACCACT,TCAGA
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,NC_000007.14,117675860,C,T
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,NC_000007.14,117479128,T,G

In [41]:
clinvar["Germline classification"].value_counts()

Germline classification
Pathogenic                             812
Likely pathogenic                      291
Pathogenic/Likely pathogenic           169
Benign                                  65
Benign/Likely benign                    32
Pathogenic; drug response               17
Pathogenic/Likely pathogenic; other      1
Name: count, dtype: int64

In [42]:
clinvar = clinvar[clinvar["Germline classification"].isin(["Pathogenic", "Benign", "Benign/Likely benign"])]

In [43]:
clinvar["Germline classification"].value_counts()

Germline classification
Pathogenic              812
Benign                   65
Benign/Likely benign     32
Name: count, dtype: int64

In [44]:
clinvar["cause"] = clinvar["Germline classification"].map({"Pathogenic" : 1, "Benign" : 0, "Benign/Likely benign": 0})

In [45]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,chr,spdi_pos0,ref,alt,cause
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,NC_000007.14,117479225,TTTTTTTTT,TTTTTTTT,0
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,NC_000007.14,117530897,GG,G,1
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,NC_000007.14,117675860,C,T,1
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,NC_000007.14,117479128,T,G,0
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,NC_000007.14,117480009,C,G,0

In [46]:
clinvar["ref"] = clinvar["ref"].astype(str).str.upper()
clinvar["alt"] = clinvar["alt"].astype(str).str.upper()
clinvar = clinvar[clinvar["ref"].str.fullmatch(r"[ACGT]+", na=False)]
clinvar = clinvar[clinvar["alt"].str.fullmatch(r"[ACGT]+", na=False)]

In [47]:
clinvar[clinvar["cause"].isna()]

Empty DataFrame
Columns: [Name, GRCh38Chromosome, GRCh38Location, Canonical SPDI, dbSNP ID, Variant type, Germline classification, chr, spdi_pos0, ref, alt, cause]
Index: []

In [48]:
clinvar.info()

<class 'pandas.core.frame.DataFrame'>
Index: 793 entries, 0 to 1384
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     793 non-null    object
 1   GRCh38Chromosome         793 non-null    int64
 2   GRCh38Location           793 non-null    object
 3   Canonical SPDI           793 non-null    object
 4   dbSNP ID                 744 non-null    object
 5   Variant type             793 non-null    object
 6   Germline classification  793 non-null    object
 7   chr                      793 non-null    object
 8   spdi_pos0                793 non-null    int64
 9   ref                      793 non-null    object
 10  alt                      793 non-null    object
 11  cause                    793 non-null    int64
dtypes: int64(3), object(9)
memory usage: 80.5+ KB

In [49]:
clinvar["pos"] = clinvar["spdi_pos0"] + 1

In [50]:
clinvar = clinvar.drop(columns=["spdi_pos0"], errors="ignore")

In [ ]:
matches = []
failed_examples = []

for _, row in clinvar.iterrows():
    try:
        chrom = row["chr"]          # NC_000007.14
        pos = int(row["pos"])
        ref = str(row["ref"]).upper()

        genome_ref = str(genome[chrom][pos-1:pos-1+len(ref)]).upper()
        match = (ref == genome_ref)

        matches.append(match)

        if not match and len(failed_examples) < 5:
            failed_examples.append((chrom, pos, ref, genome_ref))

    except Exception as e:
        matches.append(False)
        if len(failed_examples) < 5:
            failed_examples.append(("ERROR", str(e)))

clinvar["match"] = matches

# Stats
print("Total variants:", len(matches))
print("Match rate:", sum(matches) / len(matches))
print("Matched:", sum(matches))
print("Failed:", len(matches) - sum(matches))
print("Sample mismatches:", failed_examples)

Total variants: 793
Match rate: 1.0
Matched: 793
Failed: 0
Sample mismatches: []

In [52]:
clinvar = clinvar[clinvar["match"]]
clinvar.count()

Name                       793
GRCh38Chromosome           793
GRCh38Location             793
Canonical SPDI             793
dbSNP ID                   744
Variant type               793
Germline classification    793
chr                        793
ref                        793
alt                        793
cause                      793
pos                        793
match                      793
dtype: int64

In [53]:
clinvar["cause"].value_counts()

cause
1    697
0     96
Name: count, dtype: int64

In [ ]:
clinvar.to_csv("cleaned_datasets/clinvar_cleaned.csv", index = False)

In [55]:
print(list(cftr2.columns), list(clinvar.columns))

['Variant cDNA name', 'hgvs_genomic_grch38', 'chr', 'pos', 'ref', 'alt', 'cause'] ['Name', 'GRCh38Chromosome', 'GRCh38Location', 'Canonical SPDI', 'dbSNP ID', 'Variant type', 'Germline classification', 'chr', 'ref', 'alt', 'cause', 'pos', 'match']

In [56]:
cftr2.head()

,Variant cDNA name,hgvs_genomic_grch38,chr,pos,ref,alt,cause
0,c.1521_1523del,NC_000007.14:g.117559592_117559594del,chr7,117559590,ATCT,A,1
1,c.1624G>T,NC_000007.14:g.117587778G>T,chr7,117587778,G,T,1
2,c.1652G>A,NC_000007.14:g.117587806G>A,chr7,117587806,G,A,1
3,c.3909C>G,NC_000007.14:g.117652877C>G,chr7,117652877,C,G,1
5,c.3718-2477C>T,NC_000007.14:g.117639961C>T,chr7,117639961,C,T,1

In [57]:
clinvar.head()

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,chr,ref,alt,cause,pos,match
0,NC_000007.14:g.117479234del,7,117479226,NC_000007.14:117479225:TTTTTTTTT:TTTTTTTT,rs4148683,Deletion,Benign,NC_000007.14,TTTTTTTTT,TTTTTTTT,0,117479226,True
1,NC_000007.14:g.117530899del,7,117530898,NC_000007.14:117530897:GG:G,rs2485008786,Deletion,Pathogenic,NC_000007.14,GG,G,1,117530898,True
3,NC_000007.14:g.117675861C>T,7,117675861,NC_000007.14:117675860:C:T,rs1554398510,single nucleotide variant,Pathogenic,NC_000007.14,C,T,1,117675861,True
4,NG_016465.4:g.18346T>G,7,117479129,NC_000007.14:117479128:T:G,rs4148682,single nucleotide variant,Benign,NC_000007.14,T,G,0,117479129,True
5,NM_000492.3(CFTR):c.-85C>G,7,117480010,NC_000007.14:117480009:C:G,rs530414231,single nucleotide variant,Benign,NC_000007.14,C,G,0,117480010,True

In [60]:
cftr2["chr"] = "NC_000007.14"
clinvar["chr"] = "NC_000007.14"

In [61]:
clinvar.sample(5)

,Name,GRCh38Chromosome,GRCh38Location,Canonical SPDI,dbSNP ID,Variant type,Germline classification,chr,ref,alt,cause,pos,match
773,NM_000492.4(CFTR):c.3160C>G (p.His1054Asp),7,117611601,NC_000007.14:117611600:C:G,rs397508510,single nucleotide variant,Pathogenic,NC_000007.14,C,G,1,117611601,True
770,NM_000492.4(CFTR):c.3140-26A>G,7,117611555,NC_000007.14:117611554:A:G,rs76151804,single nucleotide variant,Pathogenic,NC_000007.14,A,G,1,117611555,True
736,NM_000492.4(CFTR):c.302T>G (p.Leu101Ter),7,117530927,NC_000007.14:117530926:T:G,rs397508484,single nucleotide variant,Pathogenic,NC_000007.14,T,G,1,117530927,True
564,NM_000492.4(CFTR):c.2491-2A>G,7,117594928,NC_000007.14:117594927:A:G,rs397508386,single nucleotide variant,Pathogenic,NC_000007.14,A,G,1,117594928,True
1277,NM_000492.4(CFTR):c.671del (p.Phe224fs),7,117535338,NC_000007.14:117535337:TT:T,rs769693190,Deletion,Pathogenic,NC_000007.14,TT,T,1,117535338,True

In [62]:
clinvar = clinvar[["chr", "pos", "ref", "alt", "cause"]]
cftr2 = cftr2[["chr", "pos", "ref", "alt", "cause"]]

In [63]:
print(clinvar.shape)
print(cftr2.shape)

(793, 5)
(1128, 5)

In [64]:
final_cftr_dataset = pd.concat([cftr2, clinvar], ignore_index = True)
final_cftr_dataset.drop_duplicates(subset = ["chr", "pos", "ref", "alt", "cause"], inplace = True)
final_cftr_dataset.head()

            chr        pos   ref alt  cause
0  NC_000007.14  117559590  ATCT   A      1
1  NC_000007.14  117587778     G   T      1
2  NC_000007.14  117587806     G   A      1
3  NC_000007.14  117652877     C   G      1
4  NC_000007.14  117639961     C   T      1

In [65]:
final_cftr_dataset.shape

(1600, 5)

In [ ]:
final_cftr_dataset.to_csv("cleaned_datasets/final_cftr_dataset.csv", index = False)

In [67]:
conflicts = final_cftr_dataset.groupby(['chr', 'pos', 'ref', 'alt'])['cause'].nunique()
conflicts[conflicts > 1].index

MultiIndex([], names=['chr', 'pos', 'ref', 'alt'])